# Generated by Django 5.1.4 on 2024-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news_images/')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=700)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('tag_1', models.CharField(max_length=100)),
                ('tag_2', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
