# Generated by Django 5.1.4 on 2025-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_start',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
