# Generated by Django 5.1.4 on 2025-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_news_date_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_start'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this blog is approved and visible on the site.', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this post is approved and visible on the site.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
