# Generated by Django 5.1.4 on 2025-10-27 19:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_news_title_studentclub_blogs_club_news_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclub',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
