# Generated by Django 5.1.4 on 2025-10-27 20:32

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_studentclub_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_start'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='studentclub',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentclub',
            name='admin',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentclub'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentclub'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_start',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='student_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
