# Generated by Django 5.1.4 on 2025-10-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blogs_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclub',
            name='header',
            field=models.ImageField(blank=True, help_text="An optional wide banner image for the club's detail page.", null=True, upload_to='club_headers/', verbose_name='Club Header (Wide)'),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='img',
            field=models.ImageField(help_text='A square logo for the club profile.', upload_to='club_logos/', verbose_name='Club Logo (Square)'),
        ),
    ]
